# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='timestamp_last_interaction',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de \xfaltima interacci\xf3n'),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='colleges',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studies',
            name='studies',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_instagram',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
