# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180521_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Hombre'), (1, 'Mujer'), (-1, '')], default=-1),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.IntegerField(choices=[(2, 'Ambos'), (1, 'Solo chicas'), (0, 'Solo chicos'), (-1, '')], default=-1),
        ),
    ]
