# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180605_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studies',
            options={'verbose_name': 'Estudio'},
        ),
        migrations.AlterField(
            model_name='colleges',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=b'default.jpg', upload_to=b'users', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.IntegerField(choices=[(3, 'Ambos'), (2, 'Solo chicas'), (1, 'Solo chicos')], default=3, verbose_name=b'Preferencia:'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set([('user_one', 'user_two')]),
        ),
    ]
