# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180607_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(default=b'default.jpg', upload_to=b'users', verbose_name='Imagen'),
        ),
    ]
