# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_chat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='attempts',
            field=models.IntegerField(default=3, verbose_name='Intentos restantes'),
        ),
    ]
